//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\NXOPEN\application\ComDiff.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: 20342
//              Version: NX 12
//              Date: 04-21-2026  (Format: mm-dd-yyyy)
//              Time: 18:37
//
//==============================================================================

#ifndef COMDIFF_H_INCLUDED
#define COMDIFF_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_TabControl.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_StringBlock.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/Annotations_Dimension.hxx>
#include "tolerance.h"

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport ComDiff
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    ComDiff();
    ~ComDiff();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the ComDiff.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::TabControl* tabControl;// Block type: Tabs Page
    NXOpen::BlockStyler::Group* jikong;// Block type: Group
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    NXOpen::BlockStyler::Button* a;// Block type: Button
    NXOpen::BlockStyler::Button* b;// Block type: Button
    NXOpen::BlockStyler::Button* c;// Block type: Button
    NXOpen::BlockStyler::Button* d;// Block type: Button
    NXOpen::BlockStyler::Button* e;// Block type: Button
    NXOpen::BlockStyler::Button* f;// Block type: Button
    NXOpen::BlockStyler::Button* g;// Block type: Button
    NXOpen::BlockStyler::Button* h;// Block type: Button
    NXOpen::BlockStyler::Button* js;// Block type: Button
    NXOpen::BlockStyler::Button* k;// Block type: Button
    NXOpen::BlockStyler::Button* m;// Block type: Button
    NXOpen::BlockStyler::Button* n;// Block type: Button
    NXOpen::BlockStyler::Button* p;// Block type: Button
    NXOpen::BlockStyler::Button* r;// Block type: Button
    NXOpen::BlockStyler::Button* s;// Block type: Button
    NXOpen::BlockStyler::Button* t;// Block type: Button
    NXOpen::BlockStyler::Button* u;// Block type: Button
    NXOpen::BlockStyler::Button* v;// Block type: Button
    NXOpen::BlockStyler::Button* x;// Block type: Button
    NXOpen::BlockStyler::Button* y;// Block type: Button
    NXOpen::BlockStyler::Button* z;// Block type: Button
    NXOpen::BlockStyler::Button* H6;// Block type: Button
    NXOpen::BlockStyler::Button* button023;// Block type: Button
    NXOpen::BlockStyler::Button* button024;// Block type: Button
    NXOpen::BlockStyler::Button* button025;// Block type: Button
    NXOpen::BlockStyler::Button* button026;// Block type: Button
    NXOpen::BlockStyler::Button* button027;// Block type: Button
    NXOpen::BlockStyler::Button* H6f5;// Block type: Button
    NXOpen::BlockStyler::Button* H6g5;// Block type: Button
    NXOpen::BlockStyler::Button* H6h5;// Block type: Button
    NXOpen::BlockStyler::Button* H6js5;// Block type: Button
    NXOpen::BlockStyler::Button* H6k5;// Block type: Button
    NXOpen::BlockStyler::Button* H6m5;// Block type: Button
    NXOpen::BlockStyler::Button* H6n5;// Block type: Button
    NXOpen::BlockStyler::Button* H6p5;// Block type: Button
    NXOpen::BlockStyler::Button* H6r5;// Block type: Button
    NXOpen::BlockStyler::Button* H6s5;// Block type: Button
    NXOpen::BlockStyler::Button* H6t5;// Block type: Button
    NXOpen::BlockStyler::Button* button039;// Block type: Button
    NXOpen::BlockStyler::Button* button040;// Block type: Button
    NXOpen::BlockStyler::Button* button041;// Block type: Button
    NXOpen::BlockStyler::Button* button042;// Block type: Button
    NXOpen::BlockStyler::Button* button043;// Block type: Button
    NXOpen::BlockStyler::Button* H7;// Block type: Button
    NXOpen::BlockStyler::Button* button045;// Block type: Button
    NXOpen::BlockStyler::Button* button046;// Block type: Button
    NXOpen::BlockStyler::Button* button047;// Block type: Button
    NXOpen::BlockStyler::Button* button048;// Block type: Button
    NXOpen::BlockStyler::Button* button049;// Block type: Button
    NXOpen::BlockStyler::Button* H7f6;// Block type: Button
    NXOpen::BlockStyler::Button* H7g6;// Block type: Button
    NXOpen::BlockStyler::Button* H7h6;// Block type: Button
    NXOpen::BlockStyler::Button* H7js6;// Block type: Button
    NXOpen::BlockStyler::Button* H7k6;// Block type: Button
    NXOpen::BlockStyler::Button* H7m6;// Block type: Button
    NXOpen::BlockStyler::Button* H7n6;// Block type: Button
    NXOpen::BlockStyler::Button* H7p6;// Block type: Button
    NXOpen::BlockStyler::Button* H7r6;// Block type: Button
    NXOpen::BlockStyler::Button* H7s6;// Block type: Button
    NXOpen::BlockStyler::Button* H7t6;// Block type: Button
    NXOpen::BlockStyler::Button* H7u6;// Block type: Button
    NXOpen::BlockStyler::Button* H7v6;// Block type: Button
    NXOpen::BlockStyler::Button* H7x6;// Block type: Button
    NXOpen::BlockStyler::Button* H7y6;// Block type: Button
    NXOpen::BlockStyler::Button* H7z6;// Block type: Button
    NXOpen::BlockStyler::Button* H81;// Block type: Button
    NXOpen::BlockStyler::Button* button067;// Block type: Button
    NXOpen::BlockStyler::Button* button068;// Block type: Button
    NXOpen::BlockStyler::Button* button069;// Block type: Button
    NXOpen::BlockStyler::Button* button070;// Block type: Button
    NXOpen::BlockStyler::Button* H8e7;// Block type: Button
    NXOpen::BlockStyler::Button* H8f7;// Block type: Button
    NXOpen::BlockStyler::Button* H8g7;// Block type: Button
    NXOpen::BlockStyler::Button* H8h7;// Block type: Button
    NXOpen::BlockStyler::Button* H8js7;// Block type: Button
    NXOpen::BlockStyler::Button* H8k7;// Block type: Button
    NXOpen::BlockStyler::Button* H8m7;// Block type: Button
    NXOpen::BlockStyler::Button* H8n7;// Block type: Button
    NXOpen::BlockStyler::Button* H8p7;// Block type: Button
    NXOpen::BlockStyler::Button* H8r7;// Block type: Button
    NXOpen::BlockStyler::Button* H8s7;// Block type: Button
    NXOpen::BlockStyler::Button* H8t7;// Block type: Button
    NXOpen::BlockStyler::Button* H8u7;// Block type: Button
    NXOpen::BlockStyler::Button* button084;// Block type: Button
    NXOpen::BlockStyler::Button* button085;// Block type: Button
    NXOpen::BlockStyler::Button* button086;// Block type: Button
    NXOpen::BlockStyler::Button* button087;// Block type: Button
    NXOpen::BlockStyler::Button* H82;// Block type: Button
    NXOpen::BlockStyler::Button* button089;// Block type: Button
    NXOpen::BlockStyler::Button* button090;// Block type: Button
    NXOpen::BlockStyler::Button* button091;// Block type: Button
    NXOpen::BlockStyler::Button* H8d8;// Block type: Button
    NXOpen::BlockStyler::Button* H8e8;// Block type: Button
    NXOpen::BlockStyler::Button* H8f8;// Block type: Button
    NXOpen::BlockStyler::Button* button095;// Block type: Button
    NXOpen::BlockStyler::Button* H8h8;// Block type: Button
    NXOpen::BlockStyler::Button* button097;// Block type: Button
    NXOpen::BlockStyler::Button* button098;// Block type: Button
    NXOpen::BlockStyler::Button* button099;// Block type: Button
    NXOpen::BlockStyler::Button* button0100;// Block type: Button
    NXOpen::BlockStyler::Button* button0101;// Block type: Button
    NXOpen::BlockStyler::Button* button0102;// Block type: Button
    NXOpen::BlockStyler::Button* button0103;// Block type: Button
    NXOpen::BlockStyler::Button* button0104;// Block type: Button
    NXOpen::BlockStyler::Button* button0105;// Block type: Button
    NXOpen::BlockStyler::Button* button0106;// Block type: Button
    NXOpen::BlockStyler::Button* button0107;// Block type: Button
    NXOpen::BlockStyler::Button* button0108;// Block type: Button
    NXOpen::BlockStyler::Button* button0109;// Block type: Button
    NXOpen::BlockStyler::Button* H9;// Block type: Button
    NXOpen::BlockStyler::Button* button0111;// Block type: Button
    NXOpen::BlockStyler::Button* button0112;// Block type: Button
    NXOpen::BlockStyler::Button* H9c9;// Block type: Button
    NXOpen::BlockStyler::Button* H9d9;// Block type: Button
    NXOpen::BlockStyler::Button* H9e9;// Block type: Button
    NXOpen::BlockStyler::Button* H9f9;// Block type: Button
    NXOpen::BlockStyler::Button* button0117;// Block type: Button
    NXOpen::BlockStyler::Button* H9h9;// Block type: Button
    NXOpen::BlockStyler::Button* button0119;// Block type: Button
    NXOpen::BlockStyler::Button* button0120;// Block type: Button
    NXOpen::BlockStyler::Button* button0121;// Block type: Button
    NXOpen::BlockStyler::Button* button0122;// Block type: Button
    NXOpen::BlockStyler::Button* button0123;// Block type: Button
    NXOpen::BlockStyler::Button* button0124;// Block type: Button
    NXOpen::BlockStyler::Button* button0125;// Block type: Button
    NXOpen::BlockStyler::Button* button0126;// Block type: Button
    NXOpen::BlockStyler::Button* button0127;// Block type: Button
    NXOpen::BlockStyler::Button* button0128;// Block type: Button
    NXOpen::BlockStyler::Button* button0129;// Block type: Button
    NXOpen::BlockStyler::Button* button0130;// Block type: Button
    NXOpen::BlockStyler::Button* button0131;// Block type: Button
    NXOpen::BlockStyler::Button* H10;// Block type: Button
    NXOpen::BlockStyler::Button* button0133;// Block type: Button
    NXOpen::BlockStyler::Button* button0134;// Block type: Button
    NXOpen::BlockStyler::Button* H10c10;// Block type: Button
    NXOpen::BlockStyler::Button* H10d10;// Block type: Button
    NXOpen::BlockStyler::Button* button0137;// Block type: Button
    NXOpen::BlockStyler::Button* button0138;// Block type: Button
    NXOpen::BlockStyler::Button* button0139;// Block type: Button
    NXOpen::BlockStyler::Button* H10h10;// Block type: Button
    NXOpen::BlockStyler::Button* button0141;// Block type: Button
    NXOpen::BlockStyler::Button* button0142;// Block type: Button
    NXOpen::BlockStyler::Button* button0143;// Block type: Button
    NXOpen::BlockStyler::Button* button0144;// Block type: Button
    NXOpen::BlockStyler::Button* button0145;// Block type: Button
    NXOpen::BlockStyler::Button* button0146;// Block type: Button
    NXOpen::BlockStyler::Button* button0147;// Block type: Button
    NXOpen::BlockStyler::Button* button0148;// Block type: Button
    NXOpen::BlockStyler::Button* button0149;// Block type: Button
    NXOpen::BlockStyler::Button* button0150;// Block type: Button
    NXOpen::BlockStyler::Button* button0151;// Block type: Button
    NXOpen::BlockStyler::Button* button0152;// Block type: Button
    NXOpen::BlockStyler::Button* button0153;// Block type: Button
    NXOpen::BlockStyler::Button* H11;// Block type: Button
    NXOpen::BlockStyler::Button* H11a11;// Block type: Button
    NXOpen::BlockStyler::Button* H11b11;// Block type: Button
    NXOpen::BlockStyler::Button* H11c11;// Block type: Button
    NXOpen::BlockStyler::Button* H11d11;// Block type: Button
    NXOpen::BlockStyler::Button* button0159;// Block type: Button
    NXOpen::BlockStyler::Button* button0160;// Block type: Button
    NXOpen::BlockStyler::Button* button0161;// Block type: Button
    NXOpen::BlockStyler::Button* H11h11;// Block type: Button
    NXOpen::BlockStyler::Button* button0163;// Block type: Button
    NXOpen::BlockStyler::Button* button0164;// Block type: Button
    NXOpen::BlockStyler::Button* button0165;// Block type: Button
    NXOpen::BlockStyler::Button* button0166;// Block type: Button
    NXOpen::BlockStyler::Button* button0167;// Block type: Button
    NXOpen::BlockStyler::Button* button0168;// Block type: Button
    NXOpen::BlockStyler::Button* button0169;// Block type: Button
    NXOpen::BlockStyler::Button* button0170;// Block type: Button
    NXOpen::BlockStyler::Button* button0171;// Block type: Button
    NXOpen::BlockStyler::Button* button0172;// Block type: Button
    NXOpen::BlockStyler::Button* button0173;// Block type: Button
    NXOpen::BlockStyler::Button* button0174;// Block type: Button
    NXOpen::BlockStyler::Button* button0175;// Block type: Button
    NXOpen::BlockStyler::Button* H12;// Block type: Button
    NXOpen::BlockStyler::Button* button0177;// Block type: Button
    NXOpen::BlockStyler::Button* H12b12;// Block type: Button
    NXOpen::BlockStyler::Button* button0179;// Block type: Button
    NXOpen::BlockStyler::Button* button0180;// Block type: Button
    NXOpen::BlockStyler::Button* button0181;// Block type: Button
    NXOpen::BlockStyler::Button* button0182;// Block type: Button
    NXOpen::BlockStyler::Button* button0183;// Block type: Button
    NXOpen::BlockStyler::Button* H12h12;// Block type: Button
    NXOpen::BlockStyler::Group* jizhou;// Block type: Group
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::Button* button01;// Block type: Button
    NXOpen::BlockStyler::Button* A;// Block type: Button
    NXOpen::BlockStyler::Button* B;// Block type: Button
    NXOpen::BlockStyler::Button* C;// Block type: Button
    NXOpen::BlockStyler::Button* D;// Block type: Button
    NXOpen::BlockStyler::Button* E;// Block type: Button
    NXOpen::BlockStyler::Button* F;// Block type: Button
    NXOpen::BlockStyler::Button* G;// Block type: Button
    NXOpen::BlockStyler::Button* H;// Block type: Button
    NXOpen::BlockStyler::Button* JS;// Block type: Button
    NXOpen::BlockStyler::Button* K;// Block type: Button
    NXOpen::BlockStyler::Button* M;// Block type: Button
    NXOpen::BlockStyler::Button* N;// Block type: Button
    NXOpen::BlockStyler::Button* P;// Block type: Button
    NXOpen::BlockStyler::Button* R;// Block type: Button
    NXOpen::BlockStyler::Button* S;// Block type: Button
    NXOpen::BlockStyler::Button* T;// Block type: Button
    NXOpen::BlockStyler::Button* U;// Block type: Button
    NXOpen::BlockStyler::Button* V;// Block type: Button
    NXOpen::BlockStyler::Button* X;// Block type: Button
    NXOpen::BlockStyler::Button* Y;// Block type: Button
    NXOpen::BlockStyler::Button* Z;// Block type: Button
    NXOpen::BlockStyler::Button* h5;// Block type: Button
    NXOpen::BlockStyler::Button* button029;// Block type: Button
    NXOpen::BlockStyler::Button* button030;// Block type: Button
    NXOpen::BlockStyler::Button* button031;// Block type: Button
    NXOpen::BlockStyler::Button* button032;// Block type: Button
    NXOpen::BlockStyler::Button* button033;// Block type: Button
    NXOpen::BlockStyler::Button* F6h5;// Block type: Button
    NXOpen::BlockStyler::Button* G6h5;// Block type: Button
    NXOpen::BlockStyler::Button* H6h51;// Block type: Button
    NXOpen::BlockStyler::Button* JS6h5;// Block type: Button
    NXOpen::BlockStyler::Button* K6h5;// Block type: Button
    NXOpen::BlockStyler::Button* M6h5;// Block type: Button
    NXOpen::BlockStyler::Button* N6h5;// Block type: Button
    NXOpen::BlockStyler::Button* P6h5;// Block type: Button
    NXOpen::BlockStyler::Button* R6h5;// Block type: Button
    NXOpen::BlockStyler::Button* S6h5;// Block type: Button
    NXOpen::BlockStyler::Button* T6h5;// Block type: Button
    NXOpen::BlockStyler::Button* button055;// Block type: Button
    NXOpen::BlockStyler::Button* button056;// Block type: Button
    NXOpen::BlockStyler::Button* button057;// Block type: Button
    NXOpen::BlockStyler::Button* button059;// Block type: Button
    NXOpen::BlockStyler::Button* button060;// Block type: Button
    NXOpen::BlockStyler::Button* h6;// Block type: Button
    NXOpen::BlockStyler::Button* button062;// Block type: Button
    NXOpen::BlockStyler::Button* button063;// Block type: Button
    NXOpen::BlockStyler::Button* button064;// Block type: Button
    NXOpen::BlockStyler::Button* button065;// Block type: Button
    NXOpen::BlockStyler::Button* button066;// Block type: Button
    NXOpen::BlockStyler::Button* F7h6;// Block type: Button
    NXOpen::BlockStyler::Button* G7h6;// Block type: Button
    NXOpen::BlockStyler::Button* H7h62;// Block type: Button
    NXOpen::BlockStyler::Button* JS7h6;// Block type: Button
    NXOpen::BlockStyler::Button* K7h6;// Block type: Button
    NXOpen::BlockStyler::Button* M7h6;// Block type: Button
    NXOpen::BlockStyler::Button* N7h6;// Block type: Button
    NXOpen::BlockStyler::Button* P7h6;// Block type: Button
    NXOpen::BlockStyler::Button* R7h6;// Block type: Button
    NXOpen::BlockStyler::Button* S7h6;// Block type: Button
    NXOpen::BlockStyler::Button* T7h6;// Block type: Button
    NXOpen::BlockStyler::Button* U7h6;// Block type: Button
    NXOpen::BlockStyler::Button* button083;// Block type: Button
    NXOpen::BlockStyler::Button* button088;// Block type: Button
    NXOpen::BlockStyler::Button* button092;// Block type: Button
    NXOpen::BlockStyler::Button* button093;// Block type: Button
    NXOpen::BlockStyler::Button* h7;// Block type: Button
    NXOpen::BlockStyler::Button* button096;// Block type: Button
    NXOpen::BlockStyler::Button* button0110;// Block type: Button
    NXOpen::BlockStyler::Button* button0113;// Block type: Button
    NXOpen::BlockStyler::Button* button0114;// Block type: Button
    NXOpen::BlockStyler::Button* E8h7;// Block type: Button
    NXOpen::BlockStyler::Button* F8h7;// Block type: Button
    NXOpen::BlockStyler::Button* G8h7;// Block type: Button
    NXOpen::BlockStyler::Button* H8h71;// Block type: Button
    NXOpen::BlockStyler::Button* JS8h7;// Block type: Button
    NXOpen::BlockStyler::Button* K8h7;// Block type: Button
    NXOpen::BlockStyler::Button* M8h7;// Block type: Button
    NXOpen::BlockStyler::Button* N8h7;// Block type: Button
    NXOpen::BlockStyler::Button* button0155;// Block type: Button
    NXOpen::BlockStyler::Button* button0156;// Block type: Button
    NXOpen::BlockStyler::Button* button0157;// Block type: Button
    NXOpen::BlockStyler::Button* button0158;// Block type: Button
    NXOpen::BlockStyler::Button* button0162;// Block type: Button
    NXOpen::BlockStyler::Button* button0176;// Block type: Button
    NXOpen::BlockStyler::Button* button0178;// Block type: Button
    NXOpen::BlockStyler::Button* button0184;// Block type: Button
    NXOpen::BlockStyler::Button* button0185;// Block type: Button
    NXOpen::BlockStyler::Button* h8;// Block type: Button
    NXOpen::BlockStyler::Button* button0187;// Block type: Button
    NXOpen::BlockStyler::Button* button0188;// Block type: Button
    NXOpen::BlockStyler::Button* button0189;// Block type: Button
    NXOpen::BlockStyler::Button* D8h8;// Block type: Button
    NXOpen::BlockStyler::Button* E8h8;// Block type: Button
    NXOpen::BlockStyler::Button* F8h8;// Block type: Button
    NXOpen::BlockStyler::Button* button0193;// Block type: Button
    NXOpen::BlockStyler::Button* H8h81;// Block type: Button
    NXOpen::BlockStyler::Button* button0195;// Block type: Button
    NXOpen::BlockStyler::Button* button0196;// Block type: Button
    NXOpen::BlockStyler::Button* button0197;// Block type: Button
    NXOpen::BlockStyler::Button* button0198;// Block type: Button
    NXOpen::BlockStyler::Button* button0199;// Block type: Button
    NXOpen::BlockStyler::Button* button0200;// Block type: Button
    NXOpen::BlockStyler::Button* button0201;// Block type: Button
    NXOpen::BlockStyler::Button* button0202;// Block type: Button
    NXOpen::BlockStyler::Button* button0203;// Block type: Button
    NXOpen::BlockStyler::Button* button0204;// Block type: Button
    NXOpen::BlockStyler::Button* button0205;// Block type: Button
    NXOpen::BlockStyler::Button* button0206;// Block type: Button
    NXOpen::BlockStyler::Button* button0207;// Block type: Button
    NXOpen::BlockStyler::Button* h9;// Block type: Button
    NXOpen::BlockStyler::Button* button0209;// Block type: Button
    NXOpen::BlockStyler::Button* button0210;// Block type: Button
    NXOpen::BlockStyler::Button* button0211;// Block type: Button
    NXOpen::BlockStyler::Button* D9h9;// Block type: Button
    NXOpen::BlockStyler::Button* E9h9;// Block type: Button
    NXOpen::BlockStyler::Button* F9h9;// Block type: Button
    NXOpen::BlockStyler::Button* button0215;// Block type: Button
    NXOpen::BlockStyler::Button* H9h91;// Block type: Button
    NXOpen::BlockStyler::Button* button0217;// Block type: Button
    NXOpen::BlockStyler::Button* button0218;// Block type: Button
    NXOpen::BlockStyler::Button* button0219;// Block type: Button
    NXOpen::BlockStyler::Button* button0220;// Block type: Button
    NXOpen::BlockStyler::Button* button0221;// Block type: Button
    NXOpen::BlockStyler::Button* button0222;// Block type: Button
    NXOpen::BlockStyler::Button* button0223;// Block type: Button
    NXOpen::BlockStyler::Button* button0224;// Block type: Button
    NXOpen::BlockStyler::Button* button0225;// Block type: Button
    NXOpen::BlockStyler::Button* button0226;// Block type: Button
    NXOpen::BlockStyler::Button* button0227;// Block type: Button
    NXOpen::BlockStyler::Button* button0228;// Block type: Button
    NXOpen::BlockStyler::Button* button0229;// Block type: Button
    NXOpen::BlockStyler::Button* h10;// Block type: Button
    NXOpen::BlockStyler::Button* button0231;// Block type: Button
    NXOpen::BlockStyler::Button* button0232;// Block type: Button
    NXOpen::BlockStyler::Button* button0233;// Block type: Button
    NXOpen::BlockStyler::Button* D10h10;// Block type: Button
    NXOpen::BlockStyler::Button* button0235;// Block type: Button
    NXOpen::BlockStyler::Button* button0236;// Block type: Button
    NXOpen::BlockStyler::Button* button0237;// Block type: Button
    NXOpen::BlockStyler::Button* H10h101;// Block type: Button
    NXOpen::BlockStyler::Button* button0239;// Block type: Button
    NXOpen::BlockStyler::Button* button0240;// Block type: Button
    NXOpen::BlockStyler::Button* button0241;// Block type: Button
    NXOpen::BlockStyler::Button* button0242;// Block type: Button
    NXOpen::BlockStyler::Button* button0243;// Block type: Button
    NXOpen::BlockStyler::Button* button0244;// Block type: Button
    NXOpen::BlockStyler::Button* button0245;// Block type: Button
    NXOpen::BlockStyler::Button* button0246;// Block type: Button
    NXOpen::BlockStyler::Button* button0247;// Block type: Button
    NXOpen::BlockStyler::Button* button0248;// Block type: Button
    NXOpen::BlockStyler::Button* button0249;// Block type: Button
    NXOpen::BlockStyler::Button* button0250;// Block type: Button
    NXOpen::BlockStyler::Button* button0251;// Block type: Button
    NXOpen::BlockStyler::Button* h11;// Block type: Button
    NXOpen::BlockStyler::Button* A11h11;// Block type: Button
    NXOpen::BlockStyler::Button* B11h11;// Block type: Button
    NXOpen::BlockStyler::Button* C11h11;// Block type: Button
    NXOpen::BlockStyler::Button* D11h11;// Block type: Button
    NXOpen::BlockStyler::Button* button0257;// Block type: Button
    NXOpen::BlockStyler::Button* button0258;// Block type: Button
    NXOpen::BlockStyler::Button* button0259;// Block type: Button
    NXOpen::BlockStyler::Button* H11h111;// Block type: Button
    NXOpen::BlockStyler::Button* button0261;// Block type: Button
    NXOpen::BlockStyler::Button* button0262;// Block type: Button
    NXOpen::BlockStyler::Button* button0263;// Block type: Button
    NXOpen::BlockStyler::Button* button0264;// Block type: Button
    NXOpen::BlockStyler::Button* button0265;// Block type: Button
    NXOpen::BlockStyler::Button* button0266;// Block type: Button
    NXOpen::BlockStyler::Button* button0267;// Block type: Button
    NXOpen::BlockStyler::Button* button0268;// Block type: Button
    NXOpen::BlockStyler::Button* button0269;// Block type: Button
    NXOpen::BlockStyler::Button* button0270;// Block type: Button
    NXOpen::BlockStyler::Button* button0271;// Block type: Button
    NXOpen::BlockStyler::Button* button0272;// Block type: Button
    NXOpen::BlockStyler::Button* button0273;// Block type: Button
    NXOpen::BlockStyler::Button* h12;// Block type: Button
    NXOpen::BlockStyler::Button* button0275;// Block type: Button
    NXOpen::BlockStyler::Button* B12h12;// Block type: Button
    NXOpen::BlockStyler::Button* button0277;// Block type: Button
    NXOpen::BlockStyler::Button* button0278;// Block type: Button
    NXOpen::BlockStyler::Button* button0279;// Block type: Button
    NXOpen::BlockStyler::Button* button0280;// Block type: Button
    NXOpen::BlockStyler::Button* button0281;// Block type: Button
    NXOpen::BlockStyler::Button* H12h121;// Block type: Button
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* max;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* min;// Block type: Double
    NXOpen::BlockStyler::StringBlock* kong;// Block type: String
    NXOpen::BlockStyler::StringBlock* zhou;// Block type: String
    NXOpen::BlockStyler::DoubleBlock* spck;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* spcz;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* xpck;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* xpcz;// Block type: Double
    NXOpen::BlockStyler::Toggle* k1;// Block type: Toggle
    NXOpen::BlockStyler::Toggle* z1;// Block type: Toggle

    std::string selectedFit;
    FitResult currentFitResult;
    bool hasComputedResult;
    NXOpen::Annotations::Dimension* selectedDimension;
    double selectedSize;
    bool hasSelectedDimension;

    void disableNonSelectableButtons();
    void setToggleValue(const char* blockId, bool value);
    bool getToggleValue(const char* blockId);
    void setStringValue(const char* blockId, const std::string& value);
    void setDoubleValue(const char* blockId, double value);
    void clearResultBlocks();
    void promptAndCacheDimension();
    void setSelectedFit(const std::string& fit);
    bool handleFitButtonClicked(NXOpen::BlockStyler::UIBlock* block);
    void refreshResultBySelectedFit();
    void applySelectedFitToDimension();
};
#endif //COMDIFF_H_INCLUDED
