//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\20342\Desktop\新建文件夹\canshuhua.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: 20342
//              Version: NX 12
//              Date: 03-29-2026  (Format: mm-dd-yyyy)
//              Time: 16:59
//
//==============================================================================

#ifndef CANSHUHUA_H_INCLUDED
#define CANSHUHUA_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <uf_modl.h>
#include <iostream>
#include <cstring>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
// Mandatory UF Includes
#include <uf.h>
#include <uf_object_types.h>
// Internal Includes
#include <NXOpen/ListingWindow.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/UI.hxx>
#include <uf_curve.h>
#include <uf_obj.h>
#include <windows.h>
#undef CreateDialog


// Internal+External Includes
#include <NXOpen/Annotations.hxx>
#include <NXOpen/Assemblies_Component.hxx>
#include <NXOpen/Assemblies_ComponentAssembly.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/BodyCollection.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Line.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/Session.hxx>
#include <uf.h>
#include <uf_cfi.h>
#include <uf_draw.h>
#include <uf_part.h>
#include <uf_view.h>
#include <uf_drf_types.h>
#include <uf_drf.h> 
#include <cstring>
#include <NXOpen/DraftingManager.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/Line.hxx>
#include <NXOpen/Annotations_Note.hxx>
#include <NXOpen/Annotations_Annotation.hxx>
#include <NXOpen/Annotations_LetteringPreferences.hxx>
#include <NXOpen/NXObjectManager.hxx>
#include <NXOpen/Drafting_SettingsManager.hxx>
#include <NXOpen/Annotations_EditSettingsBuilder.hxx>
#include <NXOpen/Annotations_LetteringStyleBuilder.hxx>
#include <NXOpen/DisplayableObject.hxx>

using namespace std;
using namespace NXOpen;

// Std C++ Includes
#include <iostream>
#include <sstream>

using namespace NXOpen;
using std::string;
using std::exception;
using std::stringstream;
using std::endl;
using std::cout;
using std::cerr;

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;
using namespace NXOpen::Annotations;


class DllExport canshuhua
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    canshuhua();
    ~canshuhua();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the canshuhua.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
	int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* width;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* height;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* left;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* right;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* top;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* bottom;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* tb_width;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* tb_height;// Block type: Double
	NXOpen::BlockStyler::Enumeration* mode;// 图框类型
	NXOpen::BlockStyler::Enumeration* sheettype;// 图幅
	NXOpen::BlockStyler::Enumeration* direction;// 图纸方向
	NXOpen::BlockStyler::Enumeration* bind;// 装订边
};
#endif //CANSHUHUA_H_INCLUDED
