//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\20342\Desktop\新建文件夹\canshuhua.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 20342
//              Version: NX 12
//              Date: 03-29-2026  (Format: mm-dd-yyyy)
//              Time: 16:59 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "canshuhua.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

int g_frameType = 0;

const int FRAME_TYPE_GB_HORIZONTAL_WITH_BORDER = 0;
const int FRAME_TYPE_GB_HORIZONTAL_NO_BORDER = 1;
const int FRAME_TYPE_GB_VERTICAL_WITH_BORDER = 2;
const int FRAME_TYPE_GB_VERTICAL_NO_BORDER = 3;
const int FRAME_TYPE_CUSTOM = 4;
const int MODE_GB = 0;
const int MODE_CUSTOM = 1;
const int DIRECTION_HORIZONTAL = 0;
const int DIRECTION_VERTICAL = 1;
const int BIND_KEEP = 0;
const int BIND_REMOVE = 1;



// 文字大小定义（单位：mm）
struct TextSizeConfig
{
	// 标题栏文字大小
	double title_large = 5.0;      // 大标题
	double title_medium = 3.5;     // 中等文字
	double title_small = 2.75;      // 小文字
};
TextSizeConfig g_textSize;




//图框参数结构
struct TemplateConfig
{
	double width;
	double height;

	double margin_left;
	double margin_right;
	double margin_top;
	double margin_bottom;

	double tb_width;
	double tb_height;
};

bool is_gb_with_border(int frameType)
{
	return frameType == FRAME_TYPE_GB_HORIZONTAL_WITH_BORDER ||
		frameType == FRAME_TYPE_GB_VERTICAL_WITH_BORDER;
}

int resolve_frame_type(int modeValue, int directionValue, int bindValue)
{
	if (modeValue == MODE_CUSTOM)
	{
		return FRAME_TYPE_CUSTOM;
	}

	bool isVertical = (directionValue == DIRECTION_VERTICAL);
	bool hasBinding = (bindValue == BIND_KEEP);

	if (isVertical)
	{
		return hasBinding ? FRAME_TYPE_GB_VERTICAL_WITH_BORDER : FRAME_TYPE_GB_VERTICAL_NO_BORDER;
	}

	return hasBinding ? FRAME_TYPE_GB_HORIZONTAL_WITH_BORDER : FRAME_TYPE_GB_HORIZONTAL_NO_BORDER;
}

//中点函数
double mid(double a, double b)
{
	return (a + b) / 2.0;
}



//创建线
tag_t create_line(double x1, double y1, double x2, double y2, int lineWidth)
{
	UF_CURVE_line_t line_coords;

	line_coords.start_point[0] = x1;
	line_coords.start_point[1] = y1;
	line_coords.start_point[2] = 0.0;

	line_coords.end_point[0] = x2;
	line_coords.end_point[1] = y2;
	line_coords.end_point[2] = 0.0;

	tag_t line_tag = NULL_TAG;
	UF_CURVE_create_line(&line_coords, &line_tag);
	UF_OBJ_set_line_width(line_tag, lineWidth);

	return line_tag;
}








//创建文字（带大小参数）
tag_t create_text(double x, double y, const char* str, double textSize)
{
	tag_t note_tag = NULL_TAG;

	char* text_arr[1];
	text_arr[0] = (char*)str;
	double origin[3] = { x, y, 0.0 };

	UF_DRF_create_note(1, text_arr, origin, NULL, &note_tag);

	NXOpen::Annotations::Note* noteObj =
		dynamic_cast<NXOpen::Annotations::Note*>(
			NXOpen::NXObjectManager::Get(note_tag)
			);

	if (noteObj)
	{
		// 通过 EditSettingsBuilder 设置
		NXOpen::Part* workPart = NXOpen::Session::GetSession()->Parts()->Work();

		std::vector<NXOpen::DisplayableObject*> objects;
		objects.push_back(noteObj);

		NXOpen::Annotations::EditSettingsBuilder* builder =
			workPart->SettingsManager()->CreateAnnotationEditSettingsBuilder(objects);

		// SetGeneralTextSize
		builder->AnnotationStyle()->LetteringStyle()->SetGeneralTextSize(textSize);

		builder->Commit();
		builder->Destroy();
	}

	return note_tag;
}









//画图框
void draw_frame_gb(const TemplateConfig& config)
{
	double W = config.width;
	double H = config.height;

	// 外框
	create_line(0, 0, W, 0, 2);
	create_line(W, 0, W, H, 2);
	create_line(W, H, 0, H, 2);
	create_line(0, H, 0, 0, 2);

	//内框
	double x1 = config.margin_left;
	double y1 = config.margin_bottom;
	double x2 = W - config.margin_right;
	double y2 = H - config.margin_top;

	create_line(x1, y1, x2, y1, 1);
	create_line(x2, y1, x2, y2, 1);
	create_line(x2, y2, x1, y2, 1);
	create_line(x1, y2, x1, y1, 1);

	//左上角分区
	double box_h = 12.0;
	double box_w = 60.0;

	create_line(x1, y2 - box_h, x1 + box_w, y2 - box_h, 2);
	create_line(x1 + box_w, y2 - box_h, x1 + box_w, y2, 2);

	//右下角标题栏外框（仅国标模式绘制）
	if (g_frameType != FRAME_TYPE_CUSTOM)
	{
		double tb_w = 180.0;
		double tb_h = 56.0;

		create_line(x2 - tb_w, y1, x2 - tb_w, y1 + tb_h, 1);
		create_line(x2 - tb_w, y1 + tb_h, x2, y1 + tb_h, 1);
	}

	if (is_gb_with_border(g_frameType))
	{
		double y_current = y1;
		double heights[] = { 0, 10.0, 7.0, 10.0, 7.0, 10.0, 7.0, 10.0, 7.0, 10.0, 7.0 };

		for (int i = 0; i < 11; i++)
		{
			y_current += heights[i];
			create_line(0.0, y_current, x1, y_current, 2);
		}
	}
}















//画标题栏
void draw_title_block(const TemplateConfig& config)
{
	if (g_frameType == FRAME_TYPE_CUSTOM)
	{
		double x_min = config.margin_left;
		double x_max = config.width - config.margin_right;

		double y_min = config.margin_bottom;
		double y_max = config.height - config.margin_top;

		double tb_w = config.tb_width;
		double tb_h = config.tb_height;

		//  右下角固定
		double x2 = x_max;
		double y1 = y_min;

		double x1 = x2 - tb_w;
		double y2 = y1 + tb_h;

		// 绘制自定义标题栏
		create_line(x1, y1, x2, y1, 1);
		create_line(x2, y1, x2, y2, 1);
		create_line(x2, y2, x1, y2, 1);
		create_line(x1, y2, x1, y1, 1);

		create_text((x1 + x2) / 2, (y1 + y2) / 2, "自定义标题栏" , g_textSize.title_large);

		return;  // 跳过后续国标绘制部分
	}

	//如果是国标部分（frameType != 2），绘制国标部分
	double x2 = config.width - config.margin_right;
	double y1 = config.margin_bottom;

	// 标题栏总尺寸
	double tb_w = 180.0;
	double tb_h = 56.0;

	// 标题栏左边界
	double tb_x0 = x2 - tb_w;
	double tb_x5 = x2;

	double tb_y0 = y1;
	double tb_y3 = y1 + tb_h;

	// 最右侧列（宽50）
	double right_w = 50.0;
	double x_right0 = tb_x5 - right_w; // 这一列的左边界

	// 高度分段：18 / 20 / 18
	double y_top = tb_y3;
	double y_mid1 = y_top - 18.0;
	double y_mid2 = y_mid1 - 20.0;
	double y_bottom = tb_y0;

	// 竖线（左边界）
	create_line(x_right0, y_bottom, x_right0, y_top, 2);

	// 横线（分三块）
	create_line(x_right0, y_mid1, tb_x5, y_mid1, 2);
	create_line(x_right0, y_mid2, tb_x5, y_mid2, 2);

	// 中间部分
	double x_mid_right = x_right0;   // 就是刚才那一列的左边
	double x_mid_left = x_mid_right - 50.0; // 材料标记总宽 50

	// Y方向基准（和标题栏一致）
	double y_top_all = tb_y3;
	double y_bottom_all = tb_y0;

	// 1️⃣ 最上面：50 × 28
	double y1_top = y_top_all;
	double y1_bottom = y1_top - 28.0;

	create_line(x_mid_left, y1_bottom, x_mid_right, y1_bottom, 2);

	// 2️⃣ 第二行：26 / 12 / 12 （高10）
	double y2_top = y1_bottom;
	double y2_bottom = y2_top - 10.0;

	// 竖分割
	double x_m1 = x_mid_left + 26.0;
	double x_m2 = x_m1 + 12.0;

	create_line(x_m1, y2_bottom, x_m1, y2_top, 2);
	create_line(x_m2, y2_bottom, x_m2, y2_top, 2);

	// 横线
	create_line(x_mid_left, y2_bottom, x_mid_right, y2_bottom, 2);

	// 3️⃣ 第三行：4个6.5 + 12 + 12 （高9）
	double y3_top = y2_bottom;
	double y3_bottom = y3_top - 9.0;

	// 前4个小格
	double x_tmp = x_mid_left;
	for (int i = 0; i < 4; i++)
	{
		x_tmp += 6.5;
		create_line(x_tmp, y3_bottom, x_tmp, y3_top, 2);
	}

	// 后两个 12
	double x_m3 = x_tmp + 12.0;
	double x_m4 = x_m3 + 12.0;

	create_line(x_m3, y3_bottom, x_m3, y3_top, 2);
	create_line(x_m4, y3_bottom, x_m4, y3_top, 2);

	// 横线
	create_line(x_mid_left, y3_bottom, x_mid_right, y3_bottom, 2);

	// 4️⃣ 最后一行：50 × 9
	double y4_top = y3_bottom;
	double y4_bottom = y_bottom_all;

	// （底边已存在）
	create_line(x_mid_left, y4_top, x_mid_right, y4_top, 2);

	// 左边界（整块补一条）
	create_line(x_mid_left, y_bottom_all, x_mid_left, y_top_all, 2);












	// 最左侧8行区域

	// 基准
	double xL_right = x_mid_left;
	double xL_left = xL_right - (10 + 10 + 16 + 16 + 12 + 16);

	double yL_top = tb_y3;
	double row_h = 7.0;

	// 上半部分（4行）宽：10 10 16 16 12 16
	double widths_top[6] = { 10, 10, 16, 16, 12, 16 };

	double y_curr_top = yL_top;

	for (int r = 0; r < 4; r++)
	{
		double y_next = y_curr_top - row_h;

		// 横线
		create_line(xL_left, y_next, xL_right, y_next, 2);

		// 竖线
		double x_tmp = xL_left;
		for (int i = 0; i < 5; i++)
		{
			x_tmp += widths_top[i];
			create_line(x_tmp, y_next, x_tmp, y_curr_top, 2);
		}

		y_curr_top = y_next;
	}

	// 下半部分（4行）宽：12 12 16 12 12 16
	double widths_bot[6] = { 12, 12, 16, 12, 12, 16 };

	for (int r = 0; r < 4; r++)
	{
		double y_next = y_curr_top - row_h;

		// 横线
		create_line(xL_left, y_next, xL_right, y_next, 2);

		// 竖线
		double x_tmp = xL_left;
		for (int i = 0; i < 5; i++)
		{
			x_tmp += widths_bot[i];
			create_line(x_tmp, y_next, x_tmp, y_curr_top, 2);
		}

		y_curr_top = y_next;
	}

	// 左边界补一条
	create_line(xL_left, y_curr_top, xL_left, yL_top, 2);







	//填充文字
	//右侧
	double xR = (x_right0 + tb_x5) / 2.0 - 1.0;

	create_text(xR, (y_mid1 + y_top) / 2.0, "（单位名称）", g_textSize.title_medium);
	create_text(xR, (y_mid2 + y_mid1) / 2.0, "（图样名称）", g_textSize.title_medium);
	create_text(xR, (y_bottom + y_mid2) / 2.0, "（图样代号）", g_textSize.title_medium);


	// 中间 
	double xM = (x_mid_left + x_mid_right) / 2.0 -1.0;

	// 材料标记（先当普通字放）
	create_text(xM, (y_top_all + y1_bottom) / 2.0, "（材料标记）", g_textSize.title_large);

	// 第二行
	create_text((x_mid_left + x_m1) / 2.0 , (y2_top + y2_bottom) / 2.0, "阶段标记", g_textSize.title_small);
	create_text((x_m1 + x_m2) / 2.0 , (y2_top + y2_bottom) / 2.0, "重量", g_textSize.title_small);
	create_text((x_m2 + x_mid_right) / 2.0 , (y2_top + y2_bottom) / 2.0, "比例", g_textSize.title_small);

	// 最底行
	create_text(xM, (y4_top + y_bottom_all) / 2.0, "共  张  第  张", g_textSize.title_small);



	//左侧8行区域文字填充

	// 左侧区域的X坐标范围
	double xL_left_new = tb_x0;           // 左侧区域左边界
	double xL_right_new = x_mid_left;     // 左侧区域右边界（中间区域左边界）

	// 列宽数组（上半部分4行用，第4行用）
	double widths_top_new[6] = { 10, 10, 16, 16, 12, 16 };
	// 列宽数组（下半部分4行用，第5-8行用）
	double widths_bot_new[6] = { 12, 12, 16, 12, 12, 16 };

	// 计算每列的X坐标（左边界）
	double col_x_top_new[6];
	double col_x_bot_new[6];
	double x_tmp_new = xL_left_new;
	for (int i = 0; i < 6; i++) 
	{
		col_x_top_new[i] = x_tmp_new;
		x_tmp_new += widths_top_new[i];
	}
	x_tmp_new = xL_left_new;
	for (int i = 0; i < 6; i++) 
	{
		col_x_bot_new[i] = x_tmp_new;
		x_tmp_new += widths_bot_new[i];
	}

	// 计算每行的Y坐标（从上往下，行高7mm，共8行）
	// row_y_new[0] = 顶线, row_y_new[8] = 底线
	double row_y_new[9];
	row_y_new[0] = tb_y3;  // 标题栏顶线
	for (int i = 1; i <= 8; i++) 
	{
		row_y_new[i] = row_y_new[i - 1] - 7.0;
	}

	//第4行（索引 r=3，因为0起）：6个格子全填
	// 注意：第1-4行用的是 widths_top_new
	const char* row4_text[] = { "标记", "处数", "分区", "更改文件号", "签名", "年、月、日" };
	for (int i = 0; i < 6; i++) 
	{
		double cell_center_x = col_x_top_new[i] + widths_top_new[i] / 2.0;
		double cell_center_y = (row_y_new[3] + row_y_new[4]) / 2.0;
		create_text(cell_center_x, cell_center_y, row4_text[i], g_textSize.title_small);
	}

	//第5行（索引 r=4）：6个格子全填
	// 从第5行开始用 widths_bot_new
	const char* row5_text[] = { "设计", "(签名)", "(年月日)", "标准化", "(签名)", "(年月日)" };
	for (int i = 0; i < 6; i++) 
	{
		double cell_center_x = col_x_bot_new[i] + widths_bot_new[i] / 2.0;
		double cell_center_y = (row_y_new[4] + row_y_new[5]) / 2.0;
		create_text(cell_center_x, cell_center_y, row5_text[i], g_textSize.title_small);
	}

	//第6行（索引 r=5）：只填第1格（校对）
	double cell_center_y = (row_y_new[5] + row_y_new[6]) / 2.0;
	create_text(col_x_bot_new[0] + widths_bot_new[0] / 2.0, cell_center_y, "校对", g_textSize.title_small);

	//第7行（索引 r=6）：只填第1格（审核）
	cell_center_y = (row_y_new[6] + row_y_new[7]) / 2.0;
	create_text(col_x_bot_new[0] + widths_bot_new[0] / 2.0, cell_center_y, "审核", g_textSize.title_small);

	//第8行（索引 r=7）：第1格填"工艺"，第4格填"批准"
	cell_center_y = (row_y_new[7] + row_y_new[8]) / 2.0;

	// 第1格：工艺
	create_text(col_x_bot_new[0] + widths_bot_new[0] / 2.0, cell_center_y, "工艺", g_textSize.title_small);

	// 第4格：批准（从左往右数第4个格子，索引 i=3）
	double approve_x = col_x_bot_new[3] + widths_bot_new[3] / 2.0;
	create_text(approve_x, cell_center_y, "批准", g_textSize.title_small);

	if (is_gb_with_border(g_frameType))
	{
		double x_center = config.margin_left / 2.0;
		double y_current = config.margin_bottom;
		double heights[] = { 10.0, 7.0, 10.0, 7.0, 10.0, 7.0, 10.0, 7.0, 10.0, 7.0 };
		const char* labels[] = { "日 期", "签 字", "旧底图总号", "校 描", "描 图" };

		for (int i = 0; i < 5; i++)
		{
			y_current += heights[i * 2];
			double text_bottom = y_current;
			y_current += heights[i * 2 + 1];
			double text_top = y_current;

			create_text(x_center, (text_bottom + text_top) / 2.0, labels[i], g_textSize.title_small);
		}
	}







}













//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(canshuhua::theSession) = NULL;
UI *(canshuhua::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
canshuhua::canshuhua()
{
    try
    {
        // Initialize the NX Open C++ API environment
        canshuhua::theSession = NXOpen::Session::GetSession();
        canshuhua::theUI = UI::GetUI();
        theDlxFileName = "canshuhua.dlx";
        theDialog = canshuhua::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &canshuhua::apply_cb));
		theDialog->AddOkHandler(make_callback(this, &canshuhua::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &canshuhua::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &canshuhua::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &canshuhua::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
canshuhua::~canshuhua()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    canshuhua *thecanshuhua = NULL;
    try
    {
        thecanshuhua = new canshuhua();
        // The following method shows the dialog immediately
        thecanshuhua->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        canshuhua::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(thecanshuhua != NULL)
    {
        delete thecanshuhua;
        thecanshuhua = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        canshuhua::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int canshuhua::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        canshuhua::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void canshuhua::initialize_cb()
{
    try
    {
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        width = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("width"));
        height = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("height"));
        left = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("left"));
        right = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("right"));
        top = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("top"));
        bottom = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("bottom"));
        tb_width = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("tb_width"));
        tb_height = dynamic_cast<NXOpen::BlockStyler::DoubleBlock*>(theDialog->TopBlock()->FindBlock("tb_height"));
		mode = dynamic_cast<Enumeration*>(theDialog->TopBlock()->FindBlock("mode"));
		sheettype = dynamic_cast<Enumeration*>(theDialog->TopBlock()->FindBlock("sheettype"));
		direction = dynamic_cast<Enumeration*>(theDialog->TopBlock()->FindBlock("direction"));
		bind = dynamic_cast<Enumeration*>(theDialog->TopBlock()->FindBlock("bind"));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        canshuhua::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void canshuhua::dialogShown_cb()
{
	try
	{
		update_cb(mode); // 关键
	}
	catch (exception& ex)
	{
		theUI->NXMessageBox()->Show(
			"错误",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what()
		);
	}
}
//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------













int canshuhua::apply_cb()
{
	int errorCode = 0;

	try
	{
		UF_initialize();

		TemplateConfig config;
		bool useCustomDrawingSize = false;

		// 1. 读取图框类型
		PropertyList* typeProps = mode->GetProperties();
		int modeValue = typeProps->GetEnum("Value");
		delete typeProps;

		int directionValue = DIRECTION_HORIZONTAL;
		int bindValue = BIND_KEEP;
		if (modeValue == MODE_GB)
		{
			PropertyList* directionProps = direction->GetProperties();
			directionValue = directionProps->GetEnum("Value");
			delete directionProps;

			PropertyList* bindProps = bind->GetProperties();
			bindValue = bindProps->GetEnum("Value");
			delete bindProps;
		}

		int frameType = resolve_frame_type(modeValue, directionValue, bindValue);
		g_frameType = frameType;

		// 2. 国标 or 自定义
		UF_DRAW_metric_size_t size_code = UF_DRAW_A3; // 默认 A3

		if (modeValue == MODE_GB)
		{
			PropertyList* sheetProps = sheettype->GetProperties();
			int sheet = sheetProps->GetEnum("Value");
			delete sheetProps;

			bool isGbWithBorder =
				(frameType == FRAME_TYPE_GB_HORIZONTAL_WITH_BORDER ||
				 frameType == FRAME_TYPE_GB_VERTICAL_WITH_BORDER);
			bool isGbNoBorder =
				(frameType == FRAME_TYPE_GB_HORIZONTAL_NO_BORDER ||
				 frameType == FRAME_TYPE_GB_VERTICAL_NO_BORDER);
			bool isVerticalGb =
				(frameType == FRAME_TYPE_GB_VERTICAL_WITH_BORDER ||
				 frameType == FRAME_TYPE_GB_VERTICAL_NO_BORDER);

			// 图幅尺寸 + size_code
			if (sheet == 0)
			{
				config.width = 1189;
				config.height = 841;
				size_code = UF_DRAW_A0;
			}
			else if (sheet == 1)
			{
				config.width = 841;
				config.height = 594;
				size_code = UF_DRAW_A1;
			}
			else if (sheet == 2)
			{
				config.width = 594;
				config.height = 420;
				size_code = UF_DRAW_A2;
			}
			else if (sheet == 3)
			{
				config.width = 420;
				config.height = 297;
				size_code = UF_DRAW_A3;
			}
			else
			{
				config.width = 297;
				config.height = 210;
				size_code = UF_DRAW_A4;
			}

			// 国标竖行仅交换长宽，其他规则保持一致
			if (isVerticalGb)
			{
				double temp = config.width;
				config.width = config.height;
				config.height = temp;

				// NX 标准图幅代码默认按横向纸张创建，竖行时改为自定义尺寸壳子。
				useCustomDrawingSize = true;
			}

			// 国标边距按有边框/无边框区分；国际标准保持原有规则
			if (isGbWithBorder || isGbNoBorder)
			{
				bool isLargeSheet = (sheet <= 2); // A0 / A1 / A2
				double commonMargin = isLargeSheet ? 10.0 : 5.0;

				config.margin_left = isGbWithBorder ? 25.0 : commonMargin;
				config.margin_right = commonMargin;
				config.margin_top = commonMargin;
				config.margin_bottom = commonMargin;
			}
		}
		else
		{
			// 企业自定义
			config.width = width->Value();
			config.height = height->Value();

			// 企业自定义图纸直接按输入尺寸创建，不再固定套用 A0 图纸壳子。
			useCustomDrawingSize = true;

			// 自定义边距（UI输入）
			config.margin_left = left->Value();
			config.margin_right = right->Value();
			config.margin_top = top->Value();
			config.margin_bottom = bottom->Value();
		}

		// 标题栏参数（公共）
		config.tb_width = tb_width->Value();
		config.tb_height = tb_height->Value();

		// 3. 创建图纸
		tag_t drawing;

		UF_DRAW_info_t info;
		memset(&info, 0, sizeof(info));

		if (useCustomDrawingSize)
		{
			info.size_state = UF_DRAW_CUSTOM_SIZE;
			info.size.custom_size[0] = config.height;
			info.size.custom_size[1] = config.width;
		}
		else
		{
			info.size_state = UF_DRAW_METRIC_SIZE;
			info.size.metric_size_code = size_code;
		}

		info.drawing_scale = 1.0;
		info.units = UF_PART_METRIC;
		info.projection_angle = UF_DRAW_FIRST_ANGLE_PROJECTION;

		UF_DRAW_create_drawing("Custom", &info, &drawing);
		UF_DRAW_set_display_state(drawing);

		// 4. 绘制
		draw_frame_gb(config);     // 图框
		draw_title_block(config);  // 标题栏

		UF_terminate();
	}
	catch (exception& ex)
	{
		errorCode = 1;
		theUI->NXMessageBox()->Show(
			"错误",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what()
		);
	}

	return errorCode;
}









//Callback Name: update_cb
//------------------------------------------------------------------------------
int canshuhua::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
	try
	{
		if (block == mode)
		{
			PropertyList* props = mode->GetProperties();
			int type = props->GetEnum("Value");
			delete props;

			bool isCustom = (type == MODE_CUSTOM);

			if (isCustom) // 企业自定义
			{
				// 启用自定义参数
				width->SetEnable(true);
				height->SetEnable(true);
				left->SetEnable(true);
				right->SetEnable(true);
				top->SetEnable(true);
				bottom->SetEnable(true);
				tb_width->SetEnable(true);
				tb_height->SetEnable(true);

				// 禁用国标选项
				sheettype->SetEnable(false);
				direction->SetEnable(false);
				bind->SetEnable(false);
			}
			else // 国标
			{
				// 禁用自定义参数
				width->SetEnable(false);
				height->SetEnable(false);
				left->SetEnable(false);
				right->SetEnable(false);
				top->SetEnable(false);
				bottom->SetEnable(false);
				tb_width->SetEnable(false);
				tb_height->SetEnable(false);

				// 启用国标选项
				sheettype->SetEnable(true);
				direction->SetEnable(true);
				bind->SetEnable(true);
			}
		}
	}
	catch (exception& ex)
	{
		theUI->NXMessageBox()->Show(
			"错误",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what()
		);
	}

	return 0;
}







//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* canshuhua::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
int canshuhua::ok_cb()
{
	try
	{
		int errorCode = apply_cb();
		if (errorCode != 0)
		{
			return errorCode;
		}

		Session::GetSession()->ApplicationSwitchImmediate("UG_APP_DRAFTING");
	}
	catch (exception& ex)
	{
		canshuhua::theUI->NXMessageBox()->Show(
			"错误",
			NXOpen::NXMessageBox::DialogTypeError,
			ex.what()
		);
	}

	return 0;
}
