//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\NXOPEN\source\canshuhua\x64\Debug\canshuhua.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: 20342
//              Version: NX 12
//              Date: 03-30-2026  (Format: mm-dd-yyyy)
//              Time: 16:22
//
//==============================================================================

#ifndef CANSHUHUA_H_INCLUDED
#define CANSHUHUA_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport canshuhua
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    canshuhua();
    ~canshuhua();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the canshuhua.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Enumeration* sheet_type;// Block type: Enumeration
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* width;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* height;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* left;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* right;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* top;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* bottom;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* tb_width;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* tb_height;// Block type: Double
    
};
#endif //CANSHUHUA_H_INCLUDED
